Add initial project files
cyberbotics/webots-cloud-simulation-template pull request #1
Opened 2022-07-08 13:40 UTC by ygoumaz

ditto.

2022-07-08 14:28 UTC, BenjaminDeleze requested changes
Seems good, some suggestions:

2022-07-08 14:28 UTC, BenjaminDeleze commented on Dockerfile
> +FROM cyberbotics/webots:R2022b-ubuntu20.04
```suggestion
FROM cyberbotics/webots.cloud:R2022b
```

2022-07-08 14:28 UTC, BenjaminDeleze commented on README.md
> +```
I think you also need to compile the robot window.

I don't know if it make a lot of sense to put the remote_controls plugin as the user will not be able to test it in most of the case

2022-07-08 14:45 UTC, ThomasOliverKimble requested changes
Same comments as Benjamin. Minor detail: I would suggest to open the world in Webots and save it again to create a thumbnail. On save it should be a hidden file that would be uploaded to github

2022-07-11 08:40 UTC, ygoumaz commented
I have cleaned the repository and added your suggestions. I have tried to start the world on webots.cloud but unfortunately I still get the same error message telling me that it can't find the .wbt file. Can it be related to its name containing a hyphen symbol ('-') ?

2022-07-11 08:42 UTC, BenjaminDeleze commented
It could be (even so it should not), could you try to rename the world to test?

2022-07-11 08:46 UTC, BenjaminDeleze reviewed
Seems good to me, but I think we should understand and fix the problem before merging

2022-07-11 08:47 UTC, ygoumaz commented
Sure we should fix the problem, changing the name to e_puck.wbt still triggers the error message.

2022-07-11 09:13 UTC, ThomasOliverKimble commented
>  Can it be related to its name containing a hyphen symbol ('-') ?

This used to be a problem as it was fixed in `simulation.php` here #[3](https://github.com/cyberbotics/webots-cloud/pull/3)

2022-07-11 09:47 UTC, ygoumaz commented
@ThomasOliverKimble Could you check why it fails? The only reason I see is a wrong parsing of the URL, as the same project works in your own repo: https://github.com/ThomasOliverKimble/GuidedTour/blob/guided-tour/e-puck/worlds/e-puck.wbt

2022-07-12 12:14 UTC, ygoumaz commented
The issue with the world loading has been fixed in [#4874](https://github.com/cyberbotics/webots/pull/4874). The repository is now completely cleaned and works fine on webots.cloud.

2022-07-12 12:25 UTC, BenjaminDeleze approved these changes, later dismissed
Thank you!

2022-07-13 07:47 UTC, ThomasOliverKimble commented
> Sure we should fix the problem, changing the name to e_puck.wbt still triggers the error message.

fixed with webots PR #[4874](https://github.com/cyberbotics/webots/pull/4874)

2022-07-13 07:59 UTC, ygoumaz commented
I have replaced the C controller by a Python one. It should be equivalent.

2022-07-13 08:24 UTC, BenjaminDeleze approved these changes
Thank you!

2022-07-13 12:00 UTC, ThomasOliverKimble approved these changes
Thank you!

2022-07-13 14:05 UTC, merged